# Generated by Django 3.0.5 on 2023-10-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('odyesno', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventimage/')),
                ('requirements', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
